#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 3
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor,
#  Boston, MA  02110-1301, USA.

# This file is autogenerated by the command `make fix-copies`, do not edit.
from ..utils import requires_backends


LAYOUTLM_V2_PRETRAINED_MODEL_ARCHIVE_LIST = None


class LayoutLMv2Model:
    def __init__(self, *args, **kwargs):
        requires_backends(self, ["detectron2"])

    @classmethod
    def from_pretrained(cls, *args, **kwargs):
        requires_backends(cls, ["detectron2"])
