#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 3
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor,
#  Boston, MA  02110-1301, USA.

# This file is autogenerated by the command `make fix-copies`, do not edit.
# flake8: noqa
from ..utils import DummyObject, requires_backends


class ASTFeatureExtractor(metaclass=DummyObject):
    _backends = ["speech"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["speech"])


class MCTCTFeatureExtractor(metaclass=DummyObject):
    _backends = ["speech"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["speech"])


class Speech2TextFeatureExtractor(metaclass=DummyObject):
    _backends = ["speech"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["speech"])
